### PR TITLE
support for Z-Turn board is added

### PR DESCRIPTION
**Pull request by Rooholla-Khorrambakht**
In this work I've added the support for Z-Turn board (The 7020 version).
[product link](http://www.myirtech.com/list.asp?id=502)

### CODE REVIEW

**Comment by schelleg** [comment]
hi @Rooholla-Khorrambakht 

This looks like an awesome addition - we would like to help you build out an independent PYNQ-board repo for Z-turn.   

We haven't added too many boards into this repo and are moving towards board-only repos that **depend** on PYNQ.    I'll contact you directly to see how we can help prep that.  We're updating our contributor pages to guide others towards board-only repos.  Our best example is here from Avnet: https://github.com/Avnet/Ultra96-PYNQ

**Comment by Rooholla-Khorrambakht** [comment]
Hello @schelleg 
Thanks for your kind response. Honestly I'm relatively new to github thus I'll be glad to get your help for sharing this. I believe the PYNQ platform is a really great tool and It would be awesome if more and more boards would be supported. I'll be waiting for your instructions on how to create that repository.

**Comment by schelleg** [comment]
The confusion is our fault - thanks for the contribution and we'll sort out the board repo.  Time for me to buy a Z-turn.

**Comment by schelleg** [comment]
taking this offline ... will close for now.

**Pull request closed without merging**
