### PR TITLE
Fix 18.04 native builds

### PR DESCRIPTION
**Pull request by powderluv**
Reintroduce the per ubuntu host package version check.

### CODE REVIEW

**Comment by powderluv** [comment]
Fixes #989

**Comment by yunqu** [comment]
Hi @powderluv , if you install `gcc-multilib-arm-linux-gnueabihf` instead of `gcc-multilib` in `setup_host.sh`, you will not be able to install petalinux directly. You will still have to install `gcc-multilib` first since `gcc-multilib` is a direct requirement for petalinux. So your flow looks like this:

1. install `gcc-multilib-arm-linux-gnueabihf` first
2. install `gcc-multilib`, which overwrites the 1st step.
3. install petalinux.
4. install back `gcc-multilib-arm-linux-gnueabihf` for make to work.

This looks too much. I did not see problem after installing `gcc-multilib` only, but if you do see a problem, I think we need to adjust the check_env, instead of playing with those packages?

**Comment by powderluv** [comment]
I think step one is not required. You can start at step 2. But yeah it is a pain because of petalinux requiring gcc-multilib.  Is there any forum we external folks can file a report on. I'll post on the forums. 

You can't just adjust just check_env since in the Makefile we are checking for 

checkenv: $(patsubst %, qemu_check_%, $(USED_ARCH))
        vivado -version | fgrep ${KERNEL_VERSION}
        xsdk -version | fgrep ${KERNEL_VERSION}
        which petalinux-config
        which arm-linux-gnueabihf-gcc


So you have to either modify Makefile or setup_host .  Either is fine.

**Comment by powderluv** [comment]
btw xsdk is gone in 2019.2 so we have to update this Makefile anyway soon.

**Comment by yunqu** [comment]
@powderluv I meant to change the checkenv in the makefile. But let me investigate this a little bit. I will try again tonight with fresh VMs. From what I have remembered, I did not see any problem last time.

**Comment by yunqu** [comment]
> Reintroduce the per ubuntu host package version check.

@powderluv  At which step exactly is the build process failing?

**Comment by powderluv** [comment]
Please see https://github.com/Xilinx/PYNQ/issues/989 for exact step. It is the make command

**Pull request closed without merging**
