### PR TITLE
fix bugs in class my_new_accelerator

### PR DESCRIPTION
**Pull request by sonnyhcl**
data_address should be increased as data goes while read or write data using mmio
fix ```self.mmio.write(RAW_DATA_OFFSET, raw_data[i])``` to ```self.mmio.write(RAW_DATA_OFFSET+4*i, raw_data[i]```

### CODE REVIEW

**Comment by yunqu** [comment]
Thanks for pointing out this issue. I agree on what you have changed.

For this notebook, can you restart the kernel and rerun all the cells? In that case, the cell count will start from 1, instead of 24.

**Comment by sonnyhcl** [comment]
I have restarted the kernel and reruned the cells. 

Any more comments?

**Comment by yunqu** [comment]
That is fine. Please give us more time to merge your request.

**Comment by sonnyhcl** [comment]
Hi Rock,
Thanks for your polishing. I've also learned a lot from that.
Sonny

**Pull request merged**
