### PR TITLE
fix some bugs

### PR DESCRIPTION
**Pull request by lxzheng**
1. close issue #582
2. setup binfmt_misc
3. check DNS setting

### CODE REVIEW

**Comment by PeterOgden** [comment]
I'm somewhat wary of updating $target/run as that is bound to /run on the host but I'm happy to accept your setup_hosts.sh change. I'm looking into creating an OverlayFS or similar for $target/run so we can make changes to match the host and target Ubuntu.

**Comment by schelleg** [comment]
hi @lxzheng 

thank you for the PR - please make sure to sign the CLA

**Comment by lxzheng** [comment]
Hi @schelleg 
I already signed the CLA. But I made a mistake. I forget to set the correct email address when I push the commit. I don't know how to fix it.

**Comment by schelleg** [comment]
can you try adding the CLA signed email address to your github account?  

Others have said that works: https://github.com/cla-assistant/cla-assistant/issues/68

**Comment by lxzheng** [comment]
My github accout is the CLA signed email.
I had fixed the email issue in my repository https://github.com/lxzheng/PYNQ, but it is not any effect.

**Comment by yunqu** [comment]
I have seen the same problem before. There was nothing I could do -- close PR/ fix the commits / reopen PR might be the last resort...

**Pull request closed without merging**
