### PR TITLE
fix some setup bugs

### PR DESCRIPTION
**Pull request by lxzheng**
1. close issue #582
2. setup binfmt_misc
3. check DNS setting

### CODE REVIEW

**Comment by PeterOgden** [comment]
Sorry it's taken so long to get back to you. We are currently in the process of major changes to the sdbuild flow - would you be able to move your PR to PeterOgden/PYNQ/sdbuild_refactor and I'll get it merged in with the rest of our planned changes?

**Comment by lxzheng** [comment]
@PeterOgden Sorry, I can not find sdbuild_refactor

**Comment by yunqu** [comment]
@lxzheng  https://github.com/peterogden/PYNQ/tree/sdbuild_refactor

**Comment by schelleg** [comment]
We will try to pull this onto the sdbuild_refactor branch ... closing it here

**Pull request closed without merging**
